### PR TITLE
Fixed: server error when zero as quantity is passed (#232)

### LINKED ISSUE #232: Quantity should not be prefilled with 0 as causing server error
## Current behavior

When the quantity is prefilled with 0 and the user has not received the item, the quantity is passed is 0 causing action failure:
`Both quantity to accept and quantity to reject cannot be zero.`

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #232 

### Short Description and Why It's Useful

Passed only eligible items, i.e. items with a quantity more than zero to the action. Disabled the button if none of the items have a quantity more than zero.

### Screenshots of Visual Changes before/after (If There Are Any)

Disabled as no item has a quantity more than zero.
disabled receive
Enabled
enabled

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

### CODE REVIEW

File: src/views/PurchaseOrderDetail.vue [hunk 1]
```diff
@@ -242,11 +242,15 @@ export default defineComponent({
...
     },
     async createShipment() {
-      const resp = await this.store.dispatch('order/createPurchaseShipment', { order: this.order })
+      const eligibleItems = this.order.items.filter((item: any) => item.quantityAccepted > 0)
+      const resp = await this.store.dispatch('order/createPurchaseShipment', { items: eligibleItems, orderId: this.order.orderId })
       if (resp.status === 200 && !hasError(resp)) {
         this.router.push('/purchase-orders')
       }
     },
+    checkEligibilityForCreatingShipment() {
```
Comment (adityasharma7) [inline src/views/PurchaseOrderDetail.vue:251]:
```suggestion
    isEligibileForCreatingShipment() {
```

Comment (adityasharma7) [reply src/views/PurchaseOrderDetail.vue:251]: or `hasValidItems`

**Review by adityasharma7 — CHANGES_REQUESTED** [review]

File: src/views/PurchaseOrderDetail.vue (hunk 1 above)
Comment (k2maan) [reply src/views/PurchaseOrderDetail.vue]: Updated sir

**Review by adityasharma7 — APPROVED** [review]
