### PR TITLE
Fixed: scanning failure issue caused by empty quantity values when scanning barcode  #308

### LINKED ISSUE #308: When scanning a barcode with empty qty value(remove 0) scanning fails
## Current behavior

When a user clears the qty for a product and then scan a barcode, the scanner closes but product quantity does not update

## Expected behavior

When the scan is successful, the qty of product should always update. Also if the scanned product is not found we can display a toast message of missing product.

## Steps to reproduce the issue

1. Select a shipment and move to details page
2. Generate a barcode for a product sku
3. Empty the qty field for the product and scan the barcode
4. See that the scanner closes but the product qty is not updated

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by Ritika-Patel08**
### Related Issues

Closes #308 

### Short Description and Why It's Useful

Resolved scanning failure caused by empty quantity fields by implementing automatic quantity update when scanning barcodes added toast message display for unavailable products to enhance user feedback.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

### CODE REVIEW

File: src/store/modules/shipment/actions.ts [hunk 1]
```diff
@@ -34,11 +34,17 @@ const actions: ActionTree<ShipmentState, RootState> = {
   },
 
   async updateShipmentProductCount ({ commit, state }, payload) {
-    await state.current.items.find((item: any) => {
-      if(item.sku === payload){
-        item.quantityAccepted = parseInt(item.quantityAccepted) + 1;
+    const findItem = state.current.items.find((item:any) => item.sku === payload);
+
+    if (findItem ) {
```
Comment (amansinghbais) [inline src/store/modules/shipment/actions.ts:39]: Simply logic to avoid using nested conditions.

File: src/store/modules/shipment/actions.ts [hunk 2]
```diff
@@ -6,6 +6,7 @@ import * as types from './mutation-types'
 import { hasError, showToast } from '@/utils'
 import { translate } from '@hotwax/dxp-components'
 import emitter from '@/event-bus'
+import { Item } from "@ionic/core/dist/types/components/item/item";
```
Comment (ymaheshwari1) [inline src/store/modules/shipment/actions.ts:9]: Unwanted import

File: src/store/modules/shipment/actions.ts [hunk 3]
```diff
@@ -34,11 +35,13 @@ const actions: ActionTree<ShipmentState, RootState> = {
...
 
   async updateShipmentProductCount ({ commit, state }, payload) {
-    await state.current.items.find((item: any) => {
-      if(item.sku === payload){
-        item.quantityAccepted = parseInt(item.quantityAccepted) + 1;
-      }
-    });
+    const item = state.current.items.find((item: any)=> item.sku === payload);
+    if (item) {
+      item.quantityAccepted = item.quantityAccepted ? parseInt(item.quantityAccepted) + 1 : parseInt("0") + 1;
```
Comment (ymaheshwari1) [inline src/store/modules/shipment/actions.ts:40]:
```suggestion
      item.quantityAccepted = item.quantityAccepted ? parseInt(item.quantityAccepted) + 1 : 1;
```

File: src/store/modules/shipment/actions.ts [hunk 4]
```diff
@@ -34,11 +35,13 @@ const actions: ActionTree<ShipmentState, RootState> = {
...
+    } else {
+      showToast(translate("Product not found"));
```
Comment (ymaheshwari1) [inline src/store/modules/shipment/actions.ts:42]: Check if this is included in the locale file.

**Review by ymaheshwari1 — COMMENTED** [review]
Please check if we need to handle this case for other pages.

File: src/store/modules/shipment/actions.ts (hunk 4 above)
Comment (Ritika-Patel08) [reply src/store/modules/shipment/actions.ts:41]: Yes its included

File: src/store/modules/shipment/actions.ts (hunk 2 above)
Comment (Ritika-Patel08) [reply src/store/modules/shipment/actions.ts]: Removed this import.

File: src/store/modules/order/actions.ts [hunk 5]
```diff
@@ -41,11 +41,13 @@ const actions: ActionTree<OrderState, RootState> = {
     return resp;
   },
   async updateProductCount({ commit, state }, payload ) {
-    state.current.items.find((item: any) => {
-      if (item.internalName === payload) {
-        item.quantityAccepted = item.quantityAccepted + 1;
-      }
-    });
+    const item = state.current.items.find((item: any)=> item.internalName === payload);
```
Comment (amansinghbais) [inline src/store/modules/order/actions.ts:44]:
```suggestion
    const item = state.current.items.find((item: any) => item.internalName === payload);
```

File: src/store/modules/shipment/actions.ts [hunk 6]
```diff
@@ -34,11 +34,13 @@ const actions: ActionTree<ShipmentState, RootState> = {
   },
 
   async updateShipmentProductCount ({ commit, state }, payload) {
-    await state.current.items.find((item: any) => {
-      if(item.sku === payload){
-        item.quantityAccepted = parseInt(item.quantityAccepted) + 1;
-      }
-    });
+    const item = state.current.items.find((item: any)=> item.sku === payload);
```
Comment (amansinghbais) [inline src/store/modules/shipment/actions.ts:37]:
```suggestion
    const item = state.current.items.find((item: any) => item.sku === payload);
```

File: src/store/modules/order/actions.ts [hunk 7]
```diff
@@ -41,11 +41,13 @@ const actions: ActionTree<OrderState, RootState> = {
...
   },
   async updateProductCount({ commit, state }, payload ) {
-    state.current.items.find((item: any) => {
-      if (item.internalName === payload) {
-        item.quantityAccepted = item.quantityAccepted + 1;
-      }
-    });
+    const item = state.current.items.find((item: any) => item.internalName === payload);
+    if (item) {
+      item.quantityAccepted = item.quantityAccepted ? parseInt(item.quantityAccepted) + 1 : 1;
```
Comment (ymaheshwari1) [inline src/store/modules/order/actions.ts:46]: Need to handle this case for returns as well.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

**Review by ymaheshwari1 — APPROVED** [review]
