### PR TITLE
Fixed: toast message when closing scanner without scanning (#339)

### LINKED ISSUE #339: Toast Message Displayed Upon Closing QR Code Scanner During Product Receipt
## Current behavior
When a user closes the QR code scanner during the process of receiving shipments, purchase order (PO) products, or return products, a toast message is displayed.

## Expected behavior
Upon closing the QR code scanner without performing any scans, no toast message should be displayed to the user. The system should gracefully handle the closure of the scanner interface without unnecessary notifications or interruptions to the user's workflow.

## Description
When a user closes the QR code scanner while in the process of receiving shipments, purchase order (PO) products, or return products, a toast message is displayed. This toast message appears to be an unnecessary or unintended feature, as closing the QR code scanner does not necessarily indicate an action or event that warrants user notification. This issue may cause confusion or distraction for users, disrupting their workflow and reducing the overall usability of the system.

## Steps to reproduce the issue
Initiate the process of receiving shipments, PO products, or return products that involves using the QR code scanner.
Open the QR code scanner interface.
Close the QR code scanner without scanning any codes.
Observe that a toast message is displayed, despite no specific action or event occurring.

## Environment details
- App version: v2.23.1
- Environment: UAT

## Additional information
https://jam.dev/c/be2698d1-92ae-4a69-966b-ee35b043b130

### PR DESCRIPTION
**Pull request by amansinghbais**
### Related Issues

Closes #339

### Short Description and Why It's Useful

Added check if value scanned to stop from displaying toast when nothing scanned.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

### CODE REVIEW

File: src/store/modules/order/actions.ts [hunk 1]
```diff
@@ -41,14 +41,16 @@ const actions: ActionTree<OrderState, RootState> = {
...
   async updateProductCount({ commit, state }, payload ) {
-    const item = state.current.items.find((item: any) => item.internalName === payload);
-
-    if (item) {
-      item.quantityAccepted = item.quantityAccepted ? parseInt(item.quantityAccepted) + 1 : 1;
-      commit(types.ORDER_CURRENT_UPDATED, state.current )
-      showToast(translate("Scanned successfully.", { itemName: payload }))
-    } else {
-      showToast(translate("Failed to scan:", { itemName: payload }))
+    if (payload) {
```
Comment (ymaheshwari1) [inline src/store/modules/order/actions.ts:44]: Add this check in the scan method instead of adding it in action.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

**Review by ymaheshwari1 — APPROVED** [review]
