### PR TITLE
Fixed: Incorrect information being displayed on PO details page(#2te5khn)

### LINKED ISSUE #120: Incorrect information being displayed on PO details page
## Current behavior

Information on the PO details page is not displayed correctly like po received qty

## Expected behavior

All the information should be displayed correctly.
- When a po item is not received then `0 received` should be displayed.

## Steps to reproduce the issue

Select two POs having same product in which one of the POs does not have any received history
- Go to the PO which is not being received even once and see that only `received` is getting displayed
- Now go to the PO having same product as the previous PO and see that it have some received qty for the product
- Again move to the PO (first one) and see that now the PO has some qty in received field that is same as the second PO

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

image

### PR DESCRIPTION
**Pull request by disha1202**
### Related Issues

Closes #120 

### Short Description and Why It's Useful

Updated the code to set current shipment to default if no record found or api call fails.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

### CODE REVIEW

File: src/store/modules/order/actions.ts [hunk 1]
```diff
@@ -175,9 +177,16 @@ const actions: ActionTree<OrderState, RootState> = {
         current.poHistory.items = poHistory;
         commit(types.ORDER_CURRENT_UPDATED, current);
         return poHistory;
-      } 
+      } else {
+        const current = state.current as any
```
Comment (ymaheshwari1) [inline src/store/modules/order/actions.ts:181]: We can store the current variable before try catch block and then use it everywhere.

Comment (disha1202) [reply src/store/modules/order/actions.ts]: Made the requested change.

**Review by adityasharma7 — APPROVED** [review]

**Review by adityasharma7 — APPROVED** [review]

**Review by ymaheshwari1 — APPROVED** [review]
