### PR TITLE
Fixed: show the selected route with secondary color in the menu (#85zrx4jgc)

### LINKED ISSUE #218: Show the selected route
## Current behavior

The user cannot tell which route they're currently on by looking at the menu on the left.

## Expected behavior

The current route the user is on should be selected from the menu in the secondary theme color.

No routes shown as selected:
Screenshot 2023-04-14 at 9 36 11 AM

Reference from Job Manager:

Screenshot 2023-04-14 at 9 36 49 AM

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #218 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

### CODE REVIEW

File: src/components/Menu.vue [hunk 1]
```diff
@@ -117,4 +117,16 @@ export default defineComponent({
...
\ No newline at end of file
+</script>
+
+<style scoped>
+ion-menu.md ion-item.selected ion-icon {
+  color: var(--ion-color-secondary);
+}
+ion-menu.ios ion-item.selected ion-icon {
+  color: var(--ion-color-secondary);
+}
```
Comment (dt2patel) [inline src/components/Menu.vue:128]: do we need these other selectors if we have the generic ion-item.selected selector?

**Review by dt2patel — CHANGES_REQUESTED** [review]

File: src/components/Menu.vue (hunk 1 above)
Comment (k2maan) [reply src/components/Menu.vue]: Improved

Comment (k2maan) [reply src/components/Menu.vue]: Improved by removing unnecessary selectors.

**Review by dt2patel — APPROVED** [review]
